# These are supported funding model platforms

# GitHub Sponsors
github: [jeffryberdugox]

# Other platforms (uncomment and add your usernames as needed)

# Patreon
# patreon: your_username

# Open Collective
# open_collective: your_project

# Ko-fi
# ko_fi: your_username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: your_username

# IssueHunt
# issuehunt: your_username

# Buy Me a Coffee
# custom: https://www.buymeacoffee.com/your_username

# PayPal
# custom: https://www.paypal.me/your_username

# Custom URL (you can add multiple)
# custom: ['https://your-website.com/donate', 'https://another-site.com/support']
